### ISSUE TITLE
Animate new items

### ISSUE THREAD

**Issue by TigerwareDev** [dazinator/BlazorDeferredRemove#8]
Can you use this also to add new items and animate those? Usually you would want to be able to do both dynamically.

**Comment by dazinator** [comment]
I think this should be easy to do already, because

1. You can output / render the html for the new item immediately, just also include an initial CSS class that has the transition / animation to slowly fade in the content or whatever.


The issue only comes on removal really, because the HTML content is suddenly removed from rendering including all any classes on div's that you may have wanted to use to animate the content nicely out of existence. This package solves that issue.
